#!/usr/bin/env python3
"""Generate 80 Mayank Jain essays: 20 each humanity/parenting/financial/life."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BLOG = ROOT / "site/src/content/blog"
BLOG.mkdir(parents=True, exist_ok=True)

FACTS = {
    "lonely": ("https://www.who.int/news-room/questions-and-answers/item/social-connection", "WHO — Social connection Q&A"),
    "sg": ("https://www.hhs.gov/surgeongeneral/reports-and-publications/youth-mental-health/social-media/index.html", "U.S. Surgeon General — Social Media and Youth Mental Health"),
    "ado": ("https://www.who.int/news-room/fact-sheets/detail/adolescent-mental-health", "WHO — Mental health of adolescents"),
    "fao": ("https://www.fao.org/newsroom/detail/hunger-numbers-stubbornly-high-for-three-consecutive-years-as-global-crises-deepen--un-report/", "FAO et al. — SOFI hunger numbers 2024"),
    "air": ("https://www.who.int/health-topics/air-pollution", "WHO — Air pollution"),
    "obese": ("https://www.who.int/news-room/fact-sheets/detail/obesity-and-overweight", "WHO — Obesity and overweight"),
    "sleep": ("https://www.cdc.gov/nchs/data/databriefs/db559.pdf", "CDC NCHS — Short Sleep Duration, United States 2024"),
    "care": ("https://www.ilo.org/media/65231/download", "ILO — Care work and care jobs"),
    "fert": ("https://population.un.org/wpp/assets/Files/WPP2024_Key-Messages.pdf", "UN — World Population Prospects 2024 Key Messages"),
    "move": ("https://www.who.int/news/item/26-06-2024-nearly-1.8-billion-adults-at-risk-of-disease-from-not-doing-enough-physical-activity", "WHO — 1.8 billion adults insufficiently active"),
    "learn": ("https://www.worldbank.org/en/news/press-release/2022/06/23/70-of-10-year-olds-now-in-learning-poverty-unable-to-read-and-understand-a-simple-text", "World Bank — Learning poverty ~70%"),
    "diab": ("https://www.who.int/news-room/fact-sheets/detail/diabetes", "WHO — Diabetes fact sheet"),
    "house": ("https://www.oecd.org/content/dam/oecd/en/data/datasets/affordable-housing-database/hc1-2-housing-costs-over-income.pdf", "OECD — Housing costs over income HC1.2"),
    "childp": ("https://www.worldbank.org/en/news/press-release/2023/09/12/children-bearing-brunt-of-stalled-progress-on-extreme-poverty-reduction-worldwide-unicef-world-bank", "UNICEF & World Bank — Child extreme poverty"),
    "heat": ("https://www.who.int/news-room/questions-and-answers/item/workplace-heat-stress", "WHO — Workplace heat stress"),
    "amr": ("https://www.who.int/news-room/fact-sheets/detail/antimicrobial-resistance", "WHO — Antimicrobial resistance"),
    "care2": ("https://www.ilo.org/sites/default/files/2024-10/GEDI-STAT%20brief_formatted_28.10.24_final.pdf", "ILO — Care economy statistical brief 2024"),
}

# fact_key -> claim sentence with [^1]
CLAIM = {
    "lonely": "The WHO Commission on Social Connection estimates about one in six people globally report loneliness, with loneliness associated with on the order of 871,000 deaths a year in the period examined.[^1]",
    "sg": "The 2023 U.S. Surgeon General advisory notes social media use is nearly universal among U.S. teens (up to 95% of ages 13–17), and research it cites links more than three hours a day to roughly double the risk of certain poor mental-health outcomes.[^1]",
    "ado": "WHO estimates that one in seven adolescents aged 10–19 experiences a mental disorder.[^1]",
    "fao": "UN agencies report around 733 million people faced hunger in 2023 — about one in eleven people globally.[^1]",
    "air": "WHO estimates the combined effects of ambient and household air pollution are associated with about seven million premature deaths each year.[^1]",
    "obese": "WHO reports that in 2022, one in eight people worldwide were living with obesity, and 2.5 billion adults were overweight.[^1]",
    "sleep": "CDC data for 2024 show 30.5% of U.S. adults average less than seven hours of sleep in a 24-hour period.[^1]",
    "care": "ILO analysis finds women perform about 76.2% of unpaid care work globally, with about 16.4 billion unpaid care hours every day.[^1]",
    "fert": "UN World Population Prospects 2024: more than half of countries and areas have fertility below the replacement level of 2.1; global fertility is about 2.3, down from 3.3 around 1990.[^1]",
    "move": "WHO reports nearly 1.8 billion adults — about 31% — did not meet recommended physical activity levels in 2022.[^1]",
    "learn": "World Bank and partners estimated learning poverty in low- and middle-income countries near 70% after COVID disruptions — children unable to read and understand a simple text by age ten.[^1]",
    "diab": "WHO: adults living with diabetes rose from 200 million in 1990 to 830 million in 2022; more than half of adults aged 30+ with diabetes were not taking medication in 2022.[^1]",
    "house": "OECD defines housing cost overburden as spending more than 40% of disposable income on housing — a threshold that hits many low-income renters across member countries.[^1]",
    "childp": "UNICEF and the World Bank estimate 333 million children — about one in six — live in extreme poverty on less than US$2.15 a day.[^1]",
    "heat": "WHO notes more than 2.4 billion workers are exposed to excessive heat globally, with more than 22.85 million occupational injuries each year linked to that exposure.[^1]",
    "amr": "WHO reports bacterial antimicrobial resistance was associated with more than 4.7 million deaths globally in 2021.[^1]",
    "care2": "ILO estimates that in 2023, 708 million women cited care responsibilities as the reason for being outside the labour market.[^1]",
}


def write_essay(slug, cat, title, desc, thesis, tags, open_, claim_key, reframe, move, close):
    url, rtitle = FACTS[claim_key]
    claim = CLAIM[claim_key]
    tags_yaml = ", ".join(f'"{t}"' for t in tags)
    body = f"""---
title: "{title}"
description: "{desc}"
pubDate: 2026-08-27
author: "Mayank Jain"
tags: [{tags_yaml}]
category: {cat}
draft: false
thesis: "{thesis}"
---

{open_}

{claim}

{reframe}

{move}

{close}

## References

[^1]: {rtitle}. {url} — Accessed 2026-08-27.
"""
    (BLOG / f"{slug}.md").write_text(body, encoding="utf-8")


# (slug_suffix, title, desc, thesis, tags, fact, open, reframe, move, close)
H = [
("01-loneliness-one-in-six", "One in six is lonely", "Loneliness is measured now — not just felt.", "Loneliness is a public health fact, not a private failure.", ["loneliness", "humanity"], "lonely",
 "You can fill a city and still feel erasable. That feeling is not rare poetry.",
 "Here is the flip: the opposite of loneliness is not a crowded calendar. It is being known — one reliable person beats forty weak ties.",
 "Concrete move: schedule one real contact this week that cannot be replaced by an emoji. Protect it like a medical appointment.",
 "Belonging is infrastructure. Societies that pretend otherwise keep paying in bodies."),
("02-air-we-share", "The air we pretend is free", "Dirty air is a quiet tax on shared lungs.", "Clean air is a commons.", ["air", "health"], "air",
 "Breathing is the one subscription you cannot cancel.",
 "Pollution feels invisible until a child wheezes. Make the invisible countable.",
 "Track AQI on your commute for a week. Change time or route when it spikes — then ask what the local source is.",
 "A species that will not defend its shared lung will keep calling the damage weather."),
("03-heat-shared-fate", "Heat is no longer a season", "Climate is already a workplace.", "Heat is labour rights wearing weather.", ["climate", "work"], "heat",
 "Heat used to mean summer. Now it means shift design and whether outdoor work is survivable.",
 "Heat is not only an environment story. It is a dignity story.",
 "If you manage outdoor work, write water, shade, rest, and stop-work triggers before the next heatwave.",
 "Shared atmosphere, shared duty."),
("04-amr-quiet", "When medicine stops answering", "Resistance is already a body count.", "Antibiotics are a shared inheritance.", ["amr", "health"], "amr",
 "The terrifying future is a routine infection that shrugs at the pill.",
 "Every unnecessary antibiotic course is a withdrawal from a finite global account.",
 "Never pressure a clinician for antibiotics “just in case.” Ask what is confirmed.",
 "Civilisation can be only a working drug thick."),
("05-trust-thins", "Trust thins before systems crack", "Printed trust is not grown trust.", "Opacity is expensive.", ["trust", "institutions"], "lonely",
 "Trust is the quiet permission that lets strangers cooperate.",
 "Pair institutional fog with loneliness at population scale and you see a double fracture.",
 "Wherever you lead, publish one falsifiable claim this month — a number people can check.",
 "Grown trust beats printed trust."),
("06-youth-mental", "One in seven adolescents", "Youth distress is not a phase to wait out.", "Adolescence is a developmental storm.", ["youth", "mental"], "ado",
 "We keep treating adolescent pain like weather that will pass on its own.",
 "Youth distress is phones and sleep and belonging and whether help feels normal.",
 "If you parent, teach, or coach teens — one honest check-in a week that is not about grades.",
 "The adults we become are partly the adolescents we refused to see."),
("07-obesity-environment", "One in eight, and climbing", "Shame is cheap policy; environments are the truth.", "Bodies keep score of systems.", ["obesity", "food"], "obese",
 "If the default aisle rewards ultra-processed convenience, “discipline” is swimming upstream.",
 "Willpower matters — and so do wages, cities, and food design.",
 "Change one kitchen default this week: what is within arm’s reach at 9pm.",
 "A fair society redesigns the aisle, not only the lecture."),
("08-hunger-not-abstract", "733 million is not a chart", "Hunger should end dinner-table abstraction.", "Abundance without justice is local comfort.", ["hunger", "food"], "fao",
 "Hunger is the oldest injustice wearing new supply chains.",
 "Food abundance in one postcode and undernourishment in another is a design of power and price.",
 "If you give, fund agencies that measure outcomes; if you cook, waste less as practice, not trend.",
 "A full fridge proves your map is local — not that the world is fine."),
("09-inactivity", "1.8 billion barely move", "Chairs became the default habitat.", "Movement is being a mammal.", ["movement", "health"], "move",
 "We invented machines to spare our bodies, then wondered why the body filed a complaint.",
 "Movement is not a gym identity. It is minutes.",
 "Attach a 20-minute walk to an existing habit. Miss once, not twice.",
 "Stillness sold as comfort is often deferred disease."),
("10-diabetes-climb", "830 million and half untreated", "The quiet climb in blood sugar.", "Untreated diabetes is a systems gap.", ["diabetes", "health"], "diab",
 "Some emergencies scream. This one whispers through glucose.",
 "Detection, stigma, and access decide who gets medicine.",
 "If you are due for screening, book it. If you manage a workplace, make screening easy.",
 "The future arrives as a lab number before it arrives as a headline."),
("11-learning-species", "When ten-year-olds cannot read", "Enrollment without learning is ceremony.", "Literacy is freedom infrastructure.", ["education", "children"], "learn",
 "A child who cannot read a simple text by age ten is locked out of the map.",
 "Learning is the point — not the attendance sheet.",
 "One hour of shared reading aloud a week with a child — no screens.",
 "Species that cannot teach their young to read will not stay free long."),
("12-child-poverty", "333 million children below the line", "Childhood should not be austerity.", "Child poverty is adult policy.", ["poverty", "children"], "childp",
 "Not every parenting tip survives hunger.",
 "Child poverty is adult policy wearing small shoes.",
 "When you vote or donate, ask what reaches children — food, school, cash to caregivers.",
 "Morality is measurable at the bottom of a child’s shopping list."),
("13-care-civilisation", "16.4 billion unpaid hours a day", "Care is infrastructure, not “help.”", "GDP erases the sink.", ["care", "gender"], "care",
 "Someone is holding the baby and the elder while spreadsheets call them inactive.",
 "Care is civilisation’s hidden payroll.",
 "Name the care load in your household in hours this week. Redistribute one block.",
 "Economies that erase care will keep miscounting what keeps them alive."),
("14-fertility-below", "Below 2.1 — and still misunderstanding why", "Panic is not a policy.", "Demography follows dignity.", ["fertility", "family"], "fert",
 "Low fertility is not a morality play. It is hostile math in housing and care.",
 "People are not refusing life. Many are refusing impossible spreadsheets.",
 "If you influence housing or work policy, ask whether a young family can survive the numbers.",
 "Want more children? Make childhood less of a cliff."),
("15-sleep-public", "A third short on sleep", "Exhaustion is not a scholarship.", "Sleep is maintenance of kindness.", ["sleep", "health"], "sleep",
 "We brag about exhaustion like it proves worth.",
 "Sleep is not laziness. It is nervous-system maintenance.",
 "Phone curfew 45 minutes before bed for seven nights.",
 "A sleepless culture becomes cruel — first to itself."),
("16-screens-young", "We cannot call the feed safe", "Designers A/B test attention; children bring unfinished brains.", "Neutrality is not a safety certificate.", ["youth", "tech"], "sg",
 "“Everyone is on it” is not proof of safety.",
 "If a product cannot prove safety for children, adults should stop pretending neutrality.",
 "Delay personal social apps when you can; create tech-free zones either way.",
 "Children copy what adults cannot put down."),
("17-belonging-health", "Belonging is a health system", "Neighbours treat reasons to stay alive.", "Community is preventive medicine.", ["loneliness", "community"], "lonely",
 "Hospitals treat bodies. Belonging treats the will to return tomorrow.",
 "Community is preventive medicine with a doorbell.",
 "Restart one recurring local ritual and show up twice before judging it.",
 "Health systems that ignore belonging refill the same beds."),
("18-food-power", "Hunger after abundance", "Progress is not automatic.", "Food prices can be soft language for failure.", ["hunger", "justice"], "fao",
 "The scandal is not that Earth cannot grow food.",
 "“Food prices” often softens political failure and conflict.",
 "Follow one serious food-security briefing a month — not only slogans.",
 "Abundance without justice is a better-lit famine elsewhere."),
("19-ncd-long-emergency", "The long emergency in the body", "Slow violence of modern defaults.", "NCDs are the long emergency.", ["ncd", "health"], "obese",
 "Not every crisis explodes. Some thicken blood and shorten years.",
 "Personal responsibility matters — and so do cities and food design.",
 "Pick one lever you control and one you influence this month.",
 "The long emergency bills quietly."),
("20-owe-the-next", "What we owe the next ones", "They inherit defaults, not speeches.", "Legacy is what still works.", ["future", "youth"], "learn",
 "Children do not vote on the defaults we normalize.",
 "Legacy is not a brand film. It is what still works when you are gone.",
 "Change one default that outlives your mood — a rule, a policy, a compounding gift.",
 "Live like the next readers are already watching."),
]

P = [
("01-teen-feeds", "The feed is raising someone", "Custody of attention is the real fight.", "Algorithms compete for your child’s nervous system.", ["parenting", "tech"], "sg",
 "Your child has two rooms: the bedroom and the infinite scroll.",
 "You are not behind on tech. You are early on responsibility.",
 "Co-create a family tech contract — hours, bedrooms, consequences — and follow it yourself.",
 "Children copy what adults protect."),
("02-one-in-seven", "Their storms are statistical", "Listen before you lecture.", "Moodiness is real; so is clinical load.", ["parenting", "mental"], "ado",
 "We minimize teen storms until they become adult scars.",
 "Ask “what hurts?” before “why aren’t you trying?”",
 "Keep a clinician shortlist before crisis. Normalise help like dentistry.",
 "A silent teen is sometimes rationing words."),
("03-unpaid-care", "The second shift has a name", "Love does not make hours free.", "Fairness at home is a parenting skill.", ["parenting", "care"], "care",
 "Unpaid care is the invisible second job of family life.",
 "Unnamed work stays gendered by default.",
 "Put care tasks on a shared list with names and times.",
 "Children learn gender from who clears the plate."),
("04-sleep-debt", "Parents who never clock out", "Martyrdom snaps at children.", "Your sleep is part of their safety.", ["parenting", "sleep"], "sleep",
 "Parenting on fumes is not a virtue badge.",
 "Rested love hears better than exhausted love.",
 "Trade one evening obligation for an earlier night this week.",
 "Tired love is still love — rested love is clearer."),
("05-phones-dinner", "The third guest at the table", "Presence is a dish you serve.", "Eye contact is becoming rare.", ["parenting", "attention"], "sg",
 "A phone at dinner teaches children they are interruptible by strangers.",
 "Family meals are one of the last offline commons.",
 "Phone basket for twenty minutes of dinner — adults included.",
 "What you look at at the table becomes what they think matters."),
("06-learning-home", "Reading is home weather", "Literacy is emotional safety with an alphabet.", "Homes still decide if words feel safe.", ["parenting", "education"], "learn",
 "When schools stumble, homes remain weather systems for language.",
 "Ten pages aloud, three nights a week. Boring works.",
 "A child who is read to learns they are worth time.",
 "Shared reading is love with a spine."),
("07-child-obesity", "Weight is not a morality play", "Shame shrinks conversation.", "Kids need coaches, not critics.", ["parenting", "health"], "obese",
 "Bodies grow inside engineered foodscapes.",
 "Structure changes intake better than sermons.",
 "One family default swap — fruit visible, sugary drinks harder to reach.",
 "Coach the environment, not only the child."),
("08-extreme-poverty", "When childhood is under $2.15", "Not every tip survives hunger.", "Solidarity is part of good parenting.", ["parenting", "poverty"], "childp",
 "Advice culture often assumes a full fridge.",
 "A full lunchbox is pedagogy.",
 "Fund child-focused basics when you can; fight meal stigma when you teach.",
 "Dignity starts with calories and respect."),
("09-fertility-pressure", "The spreadsheet that blocks the crib", "Ideology is not childcare.", "Support beats slogans.", ["parenting", "fertility"], "fert",
 "“Just have kids” without housing and care is ideology.",
 "Talk money and care hours honestly with young adults you advise.",
 "Want more children in a society? Make childhood less of a financial cliff.",
 "Demography follows whether life is livable."),
("10-bedtime-scroll", "The glow that steals tomorrow", "Sleep usually loses the fight with feeds.", "Chargers belong outside bedrooms.", ["parenting", "sleep"], "sg",
 "Heavy social use and sleep problems travel together in the evidence base adults ignore.",
 "Buy alarm clocks if you must — reclaim the night.",
 "Tomorrow’s mood is last night’s screen.",
 "Protect sleep like you protect seatbelts."),
("11-homework-chat", "The WhatsApp classroom", "Not every ping is an emergency.", "Mute after 8pm.", ["parenting", "school"], "ado",
 "Parent chats become second jobs and anxiety amplifiers.",
 "Your nervous system is a parenting tool.",
 "Mute non-urgent school chats after 8pm.",
 "Urgency is often just noise in a group thread."),
("12-fathers-silence", "Silence is also a curriculum", "Boys watch what fathers may feel.", "Emotional fluency is modelled.", ["parenting", "fathers"], "ado",
 "Stigma still teaches boys to vanish inside.",
 "Name one feeling out loud this week without fixing it.",
 "Emotional fluency is a gift you model, not a lecture.",
 "Silence trains the next silence."),
("13-grandparent-gap", "The missing third adult", "Networks need tending.", "Care density falls when elders are far.", ["parenting", "family"], "lonely",
 "Loneliness hits elders and new parents alike.",
 "Schedule one intergenerational ritual — call or visit — that is not residual.",
 "Families are networks. Networks need tending.",
 "The third adult is often the difference between drowning and swimming."),
("14-care-leave", "708 million reasons outside work", "Parenting policy is labour policy.", "Flexibility is retention.", ["parenting", "work"], "care2",
 "Care keeps millions of women outside paid work — by design of systems, not by accident of love.",
 "If you employ people, treat flexible care as strategy, not perk theater.",
 "Measure promotions by caregiving status.",
 "Talent lost to unpaid care is a fiction on the books."),
("15-online-bullying", "The bruise you cannot see", "Harassment follows children home.", "Safety is a relationship.", ["parenting", "safety"], "sg",
 "Near-constant social life means near-constant exposure risk.",
 "Agree a “show me the screenshot” rule without punishing the first tell.",
 "Safety is relationship, not only settings.",
 "Children need a door out of the pile-on."),
("16-special-needs", "The marathon without a crowd", "Stamina needs company.", "Relief must be scheduled.", ["parenting", "care"], "care",
 "Care intensity rises when systems under-serve.",
 "Build a two-person relief plan — even two hours — on the calendar.",
 "Stamina needs company.",
 "Unnamed relief never arrives."),
("17-early-language", "Talk is architecture", "Quantity with warmth builds the map.", "Silence is cheap.", ["parenting", "language"], "learn",
 "Language foundations decide later reading.",
 "Narrate ordinary life to toddlers — shops, buses, cooking.",
 "Speech is infrastructure.",
 "Words early are scaffolding for everything later."),
("18-play-deficit", "Play is not a luxury add-on", "Play metabolises the world.", "Protect unstructured time.", ["parenting", "play"], "ado",
 "Overloaded kids need play as much as worksheets need margins.",
 "Protect one hour of unstructured play weekly — adult phones away.",
 "Play is how children metabolise the world.",
 "A childhood without play is a rushed adult in training."),
("19-burnout-honest", "Burnout is the body saying no", "You do not need a fake percentage.", "Ask specifically for help.", ["parenting", "burnout"], "sleep",
 "Parental exhaustion is real even without a viral statistic.",
 "Ask for help in one specific sentence this week.",
 "Strong parents are allowed to be tired out loud.",
 "Vague martyrdom helps no one."),
("20-privacy-safety", "Trust with a latch", "Control without trust becomes secrecy.", "Negotiate visibility.", ["parenting", "trust"], "sg",
 "Teens need privacy; parents need enough access to keep them alive.",
 "Shared locations for late nights; private journals untouched.",
 "Control without trust becomes secrecy. Trust without a latch becomes neglect.",
 "The latch is love with boundaries."),
]

F = [
("01-housing-overburden", "When rent eats the month", "A home that costs the future is slow eviction.", "Know your housing ratio.", ["housing", "money"], "house",
 "Shelter that consumes your future is not safety.",
 "If you are in overburden territory, treat lifestyle upgrades as threats.",
 "Calculate housing costs over disposable income this week — honestly.",
 "Money stress is often housing stress in nicer clothes."),
("02-hunger-ledger", "Hunger is a balance sheet", "733 million is an indictment.", "Distribution is the question.", ["hunger", "money"], "fao",
 "Hunger is how economics fails in the stomach.",
 "Ask how policy moves food prices for the poorest.",
 "If you invest or vote, follow food-security outcomes, not slogans.",
 "Markets that cannot feed people eventually eat trust."),
("03-child-poverty-tax", "Childhood as austerity", "Cheap childhoods become expensive adulthoods.", "Cash-plus-care matters.", ["poverty", "children"], "childp",
 "Extreme poverty still holds hundreds of millions of children.",
 "Support designs that reach caregivers of children.",
 "Moral deficit shows up as empty plates.",
 "Pay the early bill or pay the later one harder."),
("04-care-gdp", "The GDP that ignores the sink", "What we refuse to count, we refuse to fund.", "Care is productive.", ["care", "economy"], "care",
 "Unpaid care is an economy hiding in plain sight.",
 "Count care leave as infrastructure in your organisation.",
 "Price honesty begins by naming hours.",
 "Invisible payrolls still exhaust people."),
("05-diabetes-delay", "Untreated is expensive", "Late treatment is the costliest saving.", "Screen early.", ["diabetes", "health"], "diab",
 "Chronic disease untreated becomes fiscal and human debt.",
 "Fund prevention; make workplace screening easy.",
 "Delay compounds.",
 "A known number early is cheaper than a crisis late."),
("06-obesity-markets", "Selling the opposite of health", "Someone profits from the default.", "Change the basket.", ["obesity", "markets"], "obese",
 "Markets can win when bodies lose.",
 "Stop buying the story that only willpower failed.",
 "Notice who profits from the aisle.",
 "Defaults are designed — redesign yours."),
("07-learning-earnings", "Illiteracy is an economic sinkhole", "Unread children become underpaid adults.", "Fund reading recovery.", ["education", "economy"], "learn",
 "Learning poverty threatens lifetime earnings at civilisation scale.",
 "Back tutoring like infrastructure.",
 "Enrollment without reading is a hollow statistic.",
 "Underpowered readers become underpowered citizens."),
("08-rent-vs-wage", "The race wages lost", "A raise that loses to rent is theater.", "Name housing inflation.", ["housing", "wages"], "house",
 "When housing outruns wages, “work harder” is a slogan.",
 "Negotiate compensation with housing costs named out loud.",
 "Participation trophies do not pay landlords.",
 "Wage honesty includes the rent line."),
("09-food-insecurity", "Beyond empty plates", "Food security is national security.", "Build buffers.", ["food", "security"], "fao",
 "Hunger staying high for years is a stalled moral project.",
 "Household buffer of basics; support food banks that publish impact.",
 "The trolley tells the truth faster than speeches.",
 "Secure food is secure politics."),
("10-heat-wages", "Heat taxes labour’s body", "Dead workers do not ship orders.", "Rest is safety.", ["heat", "labour"], "heat",
 "Hot work without protocol is deferred injury.",
 "Price rest breaks as safety in hot trades.",
 "Water, shade, stop-work — write them down.",
 "Productivity fantasies die in heatstroke."),
("11-debt-shame", "Shame is a collection agency", "Silence protects bad products.", "Talk money once.", ["debt", "shame"], "house",
 "Financial fear thrives in silence.",
 "One honest money conversation with a trusted person this month.",
 "Shame compounds faster than interest.",
 "Secrecy is expensive."),
("12-insurance-fog", "Fine print as a business model", "Complexity can be the product.", "Rewrite the claim path.", ["insurance", "trust"], "diab",
 "Chronic disease loads meet confusing coverage.",
 "Before signing, rewrite the claim path in five plain sentences — or walk.",
 "If you cannot explain it, you do not have it.",
 "Fog is not neutrality."),
("13-care-labour", "708 million sidelined by care", "Talent lost to care is fiction.", "Measure by caregiving status.", ["care", "labour"], "care2",
 "Care responsibilities keep hundreds of millions of women outside paid work.",
 "Measure promotions by caregiving status.",
 "Retention requires care design.",
 "Sidelined talent is a national loss."),
("14-student-cost", "Education priced like luxury", "Who gets to think for a living?", "Fund learning at work.", ["education", "cost"], "learn",
 "We can underfund reading and overcharge credentials at once.",
 "Prefer employers who fund learning over those who only demand degrees.",
 "Price signals shape minds.",
 "Access is the real entrance exam."),
("15-medical-shock", "The bill after the diagnosis", "Prepared is cheaper than surprised.", "One-page meds sheet.", ["health", "bills"], "diab",
 "Health shocks become money shocks overnight.",
 "Keep meds-and-contacts on one page; know help options before emergency.",
 "Surprise is a surcharge.",
 "Paperwork is part of care."),
("16-gig-heat", "Precarity plus temperature", "Flexibility without protection is risk transfer.", "Write heat into contracts.", ["gig", "heat"], "heat",
 "Precarious outdoor work meets a hotter planet.",
 "If you hire gig labour, write heat and water into the contract.",
 "Risk transfer is not innovation.",
 "Contracts should outlive weather apps."),
("17-inflation-lived", "Inflation is a feeling first", "Charts lag the trolley.", "Track your basket.", ["inflation", "lived"], "fao",
 "Food insecurity is how inflation feels at the bottom.",
 "Track your real basket monthly, not only headlines.",
 "Policy that ignores the trolley misses the voter.",
 "Lived prices are the real index."),
("18-savings-thin", "No cushion, no choices", "Boring money beats dramatic regret.", "Automate a tiny transfer.", ["savings", "security"], "house",
 "Housing overburden leaves little room to save.",
 "Automate a tiny transfer the day income arrives.",
 "Small and sacred beats large and imaginary.",
 "Cushions create choices."),
("19-stacked-generations", "Stacked bills under one roof", "Shared roofs need shared rules.", "Write money agreements.", ["family", "money"], "fert",
 "Low fertility and housing stress reshape who can leave home.",
 "Write family money agreements before resentment does.",
 "Clarity is kindness.",
 "Stacked generations need stacked honesty."),
("20-amr-fiscal", "Resistance is a fiscal threat", "Stewardship is economic policy.", "Restraint at the counter.", ["amr", "economy"], "amr",
 "AMR already carries a massive associated death toll — costs follow.",
 "Stewardship in clinics and farms is economic policy.",
 "Cheap antibiotics tomorrow depend on restraint today.",
 "Future care budgets are being written in today’s prescriptions."),
]

L = [
("01-short-sleep", "Protect the seven", "Sleep is the cheapest performance drug.", "Same wake time.", ["sleep", "life"], "sleep",
 "Your future self is built while you are unconscious.",
 "Same wake time for seven days; let bedtime follow.",
 "Guard the night like training.",
 "Rest is not optional equipment."),
("02-move-minutes", "150 minutes is not a personality", "Minutes beat identity.", "Calendar the walks.", ["movement", "life"], "move",
 "Activity guidelines are not a vibe. They are minutes.",
 "Two 25-minute walks on the calendar like meetings.",
 "Motion is mood chemistry you can schedule.",
 "Miss the myth of perfect; keep the minutes."),
("03-obesity-shame", "Drop the mirror sermon", "Change defaults, not your name.", "One food default.", ["body", "life"], "obese",
 "Global obesity scale needs less shame and better defaults.",
 "Change one food default this week — not your entire personality.",
 "Bodies keep the score of environments.",
 "Kind structure beats cruel commentary."),
("04-diabetes-check", "Know the number", "Curiosity beats fear.", "Book screening.", ["diabetes", "life"], "diab",
 "830 million adults with diabetes is a call to know your own number.",
 "If overdue, book screening this month.",
 "A number known early is a life longer.",
 "Fear delays; facts guide."),
("05-heat-days", "Respect the thermometer", "Heroics in heat schedule funerals.", "Shift outdoor tasks.", ["heat", "life"], "heat",
 "Extreme days are safety days.",
 "Shift outdoor tasks to morning; hydrate on a timer.",
 "Respect the thermometer.",
 "Courage is knowing when to stop."),
("06-attention-vote", "Attention is a ballot", "Thumbs cast votes all day.", "One app off home screen.", ["attention", "life"], "sg",
 "What you look at becomes who you rehearse being.",
 "Remove one app from the home screen for a week.",
 "Your thumbs are casting votes.",
 "Attention is character practice."),
("07-city-loneliness", "Crowds are not company", "Proximity without contact is denser solitude.", "Walking call weekly.", ["loneliness", "life"], "lonely",
 "Cities amplify the paradox of lonely crowds.",
 "Convert one commute weekly into a walking call with a real person.",
 "Proximity is not contact.",
 "Choose company on purpose."),
("08-evening-scroll", "The false day extension", "Night is for repair.", "Grayscale after 9.", ["sleep", "tech"], "sleep",
 "Scrolling past midnight borrows tomorrow’s patience.",
 "Grayscale the phone after 9pm for a week.",
 "Night is for repair, not highlights.",
 "End the false day."),
("09-friendship", "Friendship is a practice", "Belonging decays without calendar ink.", "Monthly hold.", ["friendship", "life"], "lonely",
 "Treat friendship like health behaviour.",
 "Recurring monthly hold with one friend — non-negotiable.",
 "Love unscheduled becomes nostalgia.",
 "Practice is the point."),
("10-walk-medicine", "The oldest prescription", "Sidewalks are clinics.", "Walk the first call.", ["walking", "life"], "move",
 "Walking undercuts inactivity one step at a time.",
 "Walk the first call of the day.",
 "Sidewalks are clinics if you use them.",
 "Oldest prescription, still underfilled."),
("11-meal-alone", "Eat like someone is watching kindly", "Food tastes like company.", "One shared meal.", ["eating", "life"], "lonely",
 "Lonely eating is a modern default.",
 "One shared meal weekly — even virtual.",
 "Food tastes like company when company is present.",
 "Ritual repairs."),
("12-caffeine-curfew", "Anxiety in a cup", "Late caffeine loans against sleep.", "No caffeine after 2pm.", ["caffeine", "sleep"], "sleep",
 "When short sleep is already common, late stimulants are self-sabotage.",
 "No caffeine after 2pm for five days. Notice evenings.",
 "Calm is a performance enhancer.",
 "Curfew the cup."),
("13-standing-day", "Jobs that never sit still", "Under-recovery is the villain.", "Micro-breaks.", ["work", "body"], "move",
 "Service bodies pay an invisible tax.",
 "Micro-breaks and footwear that respect the shift.",
 "Endurance without recovery is slow injury.",
 "Respect the standing day."),
("14-weekend-warrior", "Two heroic days, five neglected", "Consistency beats confession.", "Daily sprinkle.", ["fitness", "life"], "move",
 "Binge effort does not cancel a sedentary week.",
 "Sprinkle movement daily; keep weekends for joy.",
 "Consistency beats confession.",
 "Hero weekends cannot rescue ignored weekdays."),
("15-morning-reclaim", "Own the first hour", "Who opens your day owns your day.", "No inbox 30 minutes.", ["morning", "life"], "sleep",
 "Better nights enable better mornings.",
 "No inbox in the first thirty minutes.",
 "Who opens your day owns your day.",
 "Reclaim the first hour."),
("16-grief-modern", "Grief in a culture of speed", "Unprocessed grief becomes personality.", "Ritualise anniversaries.", ["grief", "life"], "lonely",
 "A lonely world is bad at mourning.",
 "Ritualise anniversary days — walk, candle, story.",
 "Unprocessed grief becomes personality.",
 "Budget time for what hurt."),
("17-aging-body", "The long negotiation", "Independence has a muscle requirement.", "Strength twice weekly.", ["aging", "life"], "diab",
 "More years with disease unless defaults change.",
 "Strength work twice weekly — balance is freedom.",
 "Independence has a muscle requirement.",
 "Negotiate aging with training, not denial."),
("18-hydration-heat", "Water is a plan", "Thirst is a late messenger.", "Bottle before thirst.", ["heat", "life"], "heat",
 "Heat makes hydration a safety protocol.",
 "Bottle in bag before thirst argues.",
 "Thirst is a late messenger.",
 "Plan the water."),
("19-amr-personal", "Steward the prescription", "Personal convenience can become collective danger.", "Never share leftovers.", ["amr", "life"], "amr",
 "Your antibiotic story is part of a species story.",
 "Never share leftover antibiotics.",
 "Personal convenience can become collective danger.",
 "Steward the counter."),
("20-quiet-enough", "Silence as nutrient", "If you cannot be alone, you cannot be free.", "Ten minutes no input.", ["silence", "life"], "sg",
 "In a loud feed world, quiet is a health behaviour.",
 "Ten minutes daily with no input. Sit with the discomfort.",
 "If you cannot be alone, you cannot be free.",
 "Silence is nutrient, not emptiness."),
]


def run_block(prefix, cat, rows):
    for row in rows:
        suf, title, desc, thesis, tags, fact, open_, reframe, move, close = row
        write_essay(f"mj-{prefix}-{suf}", cat, title, desc, thesis, tags, open_, fact, reframe, move, close)


run_block("humanity", "humanity", H)
run_block("parenting", "parenting", P)
run_block("financial", "financial", F)
run_block("life", "life", L)

n = len(list(BLOG.glob("mj-humanity-*.md"))) + len(list(BLOG.glob("mj-parenting-*.md"))) + len(list(BLOG.glob("mj-financial-*.md"))) + len(list(BLOG.glob("mj-life-*.md")))
research = ROOT / "reports/research/2026-08-27-top20-four-categories.md"
research.parent.mkdir(parents=True, exist_ok=True)
research.write_text(
    f"# Research — Top 20 × 4 (Mayank Jain)\n\n- Date: 2026-08-27\n- Essays in mj-*- libraries: {n}\n\n## Sources\n"
    + "\n".join(f"- {t}: {u}" for u, t in FACTS.values())
    + "\n",
    encoding="utf-8",
)
print(f"OK essays tagged mj-*: {n}")
